/* Neahkahnie Atelier — hung inventory. Real Cara Mico works only. */
window.ATELIER = [
  { src: "img/neahkahnie.jpg", title: "Neahkahnie", cat: "landscapes-coast" },
  { src: "img/ocean.jpg", title: "Ocean", cat: "landscapes-coast" },
  { src: "img/the-wave.jpg", title: "The Wave", cat: "landscapes-coast" },
  { src: "img/nehalem.jpg", title: "Nehalem", cat: "landscapes-coast" },
  { src: "img/ghost.jpg", title: "Ghost", cat: "landscapes-coast" },
  { src: "img/ocean-of-flame.jpg", title: "Ocean of Flame", cat: "landscapes-coast" },
  { src: "img/pollution.jpg", title: "Pollution", cat: "landscapes-coast" },
  { src: "img/20201025-145149.jpg", title: "Night boats", cat: "landscapes-coast" },
  { src: "img/20181121-150820.jpg", title: "Marsh horizon", cat: "landscapes-coast" },
  { src: "img/20180506-122928.jpg", title: "Coastal plane", cat: "landscapes-coast" },
  { src: "img/20201024-233510.jpg", title: "Coastal drawing", cat: "landscapes-coast" },

  { src: "img/violet-flame.jpg", title: "Violet Flame", cat: "abstract-expression" },
  { src: "img/tsunami.jpg", title: "Tsunami", cat: "abstract-expression" },
  { src: "img/war.jpg", title: "War", cat: "abstract-expression" },
  { src: "img/star.jpg", title: "Star", cat: "abstract-expression" },
  { src: "img/20201024-233520.jpg", title: "Green and gold field", cat: "abstract-expression" },
  { src: "img/20201024-233453.jpg", title: "Pastel hills", cat: "abstract-expression" },
  { src: "img/20201024-233425.jpg", title: "Red cloud", cat: "abstract-expression" },
  { src: "img/img-20151029-091758.jpg", title: "Night cloud", cat: "abstract-expression" },
  { src: "img/0321232309-hdr.jpg", title: "Bell form", cat: "abstract-expression" },

  { src: "img/thistle.jpg", title: "Thistle", cat: "botanical-nature" },
  { src: "img/tree-on-recycled-paper.jpg", title: "Tree on recycled paper", cat: "botanical-nature" },
  { src: "img/20181202-131855.jpg", title: "Night tree", cat: "botanical-nature" },
  { src: "img/20200701-195408.jpg", title: "Illusion & reality", cat: "botanical-nature" },

  { src: "img/large-jelly.jpg", title: "Large Jelly", cat: "animals" },
  { src: "img/mini-jelly.jpg", title: "Mini-jelly", cat: "animals" },
  { src: "img/bird.jpg", title: "Bird", cat: "animals" },
  { src: "img/cat.jpg", title: "Cat", cat: "animals" },
  { src: "img/dog.jpg", title: "Dog", cat: "animals" },
  { src: "img/20201025-145254.jpg", title: "Jelly field", cat: "animals" },
  { src: "img/20190629-203228.jpg", title: "Figure and dragon", cat: "animals" },
  { src: "img/20201024-233433.jpg", title: "Owl and eyes", cat: "animals" },

  { src: "img/as-above-so-below.jpg", title: "As Above So Below", cat: "figure-portrait" },
  { src: "img/female-figure-oil-on-paper.jpg", title: "Female figure, oil on paper", cat: "figure-portrait" },
  { src: "img/female-figure-charcoal.jpg", title: "Female figure, charcoal", cat: "figure-portrait" },
  { src: "img/female-nude-charcoal.jpg", title: "Female nude, charcoal", cat: "figure-portrait" },
  { src: "img/female-nude-charcoal-2.jpg", title: "Female nude, charcoal II", cat: "figure-portrait" },
  { src: "img/female-portrait-oil.jpg", title: "Female portrait, oil", cat: "figure-portrait" },
  { src: "img/female-portrait-oil-2.jpg", title: "Female portrait, oil II", cat: "figure-portrait" },
  { src: "img/female-portrait-oil-3.jpg", title: "Female portrait, oil III", cat: "figure-portrait" },
  { src: "img/female-portrait-oil-4.jpg", title: "Female portrait, oil IV", cat: "figure-portrait" },
  { src: "img/female-portrait-oil-pastel.jpg", title: "Female portrait, oil pastel", cat: "figure-portrait" },
  { src: "img/female-portrait-acrylic.jpg", title: "Female portrait, acrylic", cat: "figure-portrait" },
  { src: "img/self-portrait-acrylic.jpg", title: "Self-portrait, acrylic", cat: "figure-portrait" },
  { src: "img/self-portrait-acrylic-2.jpg", title: "Self-portrait, acrylic II", cat: "figure-portrait" },
  { src: "img/self-portrait-acrylic-3.jpg", title: "Self-portrait, acrylic III", cat: "figure-portrait" },
  { src: "img/self-portrait-acrylic-4.jpg", title: "Self-portrait, acrylic IV", cat: "figure-portrait" },
  { src: "img/self-portrait-charcoal.jpg", title: "Self-portrait, charcoal", cat: "figure-portrait" },
  { src: "img/self-portrait-graphite.jpg", title: "Self-portrait, graphite", cat: "figure-portrait" },
  { src: "img/monochromatic-self-portrait-oil.jpg", title: "Monochromatic self-portrait, oil", cat: "figure-portrait" },
  { src: "img/male-portrait-oil-pastel-and-charcoal.jpg", title: "Male portrait, oil pastel and charcoal", cat: "figure-portrait" },
  { src: "img/leg-in-water-study-oil-on-paper.jpg", title: "Leg in water, oil on paper", cat: "figure-portrait" },
  { src: "img/unfinished.jpg", title: "Unfinished", cat: "figure-portrait" },
  { src: "img/20201206-134759.jpg", title: "Hair and river", cat: "figure-portrait" },
  { src: "img/0517232026.jpg", title: "Portrait sketch", cat: "figure-portrait" },
  { src: "img/0716231323.jpg", title: "Figure with sword", cat: "figure-portrait" },
  { src: "img/img-3195.jpg", title: "Fashion figure", cat: "figure-portrait" },
  { src: "img/img-20200214-214207.jpg", title: "Yellow-hair portrait", cat: "figure-portrait" },
  { src: "img/img-3197.jpg", title: "Two figures, ink", cat: "figure-portrait" },

  { src: "img/still-life-1.jpg", title: "Still life I", cat: "still-life-study" },
  { src: "img/still-life-2.jpg", title: "Still life II", cat: "still-life-study" },
  { src: "img/still-life-acrylic.jpg", title: "Still life, acrylic", cat: "still-life-study" },
  { src: "img/still-life-charcoal.jpg", title: "Still life, charcoal", cat: "still-life-study" },
  { src: "img/still-life-charcoal-2.jpg", title: "Still life, charcoal II", cat: "still-life-study" },
  { src: "img/still-life-charcoal-3.jpg", title: "Still life, charcoal III", cat: "still-life-study" },
  { src: "img/still-life-charcoal-4.jpg", title: "Still life, charcoal IV", cat: "still-life-study" },
  { src: "img/still-life-graphite.jpg", title: "Still life, graphite", cat: "still-life-study" },
  { src: "img/still-life-pencil.jpg", title: "Still life, pencil", cat: "still-life-study" },
  { src: "img/still-life-oil-pastel.jpg", title: "Still life, oil pastel", cat: "still-life-study" },
  { src: "img/cloth-study-charcoal.jpg", title: "Cloth study, charcoal", cat: "still-life-study" },
  { src: "img/composition-study.jpg", title: "Composition study", cat: "still-life-study" },
  { src: "img/img-3210.jpg", title: "Still life with lamp", cat: "still-life-study" },
  { src: "img/img-3198.jpg", title: "Studio still life", cat: "still-life-study" },
  { src: "img/img-3201.jpg", title: "Studio still life II", cat: "still-life-study" },
  { src: "img/img-3208.jpg", title: "Studio still life III", cat: "still-life-study" },

  { src: "img/mono-print.jpg", title: "Mono print", cat: "printmaking" },
  { src: "img/mono-print-2.jpg", title: "Mono print II", cat: "printmaking" },
  { src: "img/mono-print-3.jpg", title: "Mono print III", cat: "printmaking" },
  { src: "img/linoleum-print.jpg", title: "Linoleum print", cat: "printmaking" },

  { src: "img/broken.jpg", title: "Broken", cat: "mixed-media" },
  { src: "img/mixed-media.jpg", title: "Mixed media", cat: "mixed-media" },
  { src: "img/mixed-media-gouache-on-canson.jpg", title: "Gouache on Canson", cat: "mixed-media" },
  { src: "img/street-scene-charcoal-conte-marker.jpg", title: "Street scene", cat: "mixed-media" },
  { src: "img/20200504-131719.jpg", title: "Figure on the dam", cat: "mixed-media" },
  { src: "img/20200724-204038.jpg", title: "Musician sketch", cat: "mixed-media" },
  { src: "img/img-3207.jpg", title: "Industrial interior", cat: "mixed-media" },
  { src: "img/20201025-145436.jpg", title: "Ship, waves, jelly", cat: "mixed-media" }
];

window.CAT_LABEL = {
  "landscapes-coast": "Landscapes / coast",
  "abstract-expression": "Abstract / expression",
  "botanical-nature": "Botanical / nature",
  "animals": "Animals",
  "figure-portrait": "Figure / portrait",
  "still-life-study": "Still life / study",
  "printmaking": "Printmaking",
  "mixed-media": "Mixed media"
};
